# Generated by Django 4.1 on 2024-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("education", models.CharField(max_length=20)),
                ("occupation", models.CharField(max_length=20)),
                ("marital_status", models.CharField(max_length=10)),
            ],
        ),
    ]
