# Generated by Django 4.1 on 2024-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missing_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="product_rating",
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
