# Generated by Django 4.1 on 2024-04-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missing_data", "0002_person_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="id",
        ),
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="customer_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
