# Generated by Django 4.1 on 2024-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missing_data", "0004_alter_person_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="customer_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
