# Generated by Django 4.1 on 2024-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missing_data", "0005_alter_person_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="education",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="marital_status",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="occupation",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="product_rating",
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
